### ISSUE TITLE
Source repo of the library?

### ISSUE THREAD

**Issue by IzzySoft** [OneB1ank/A1Memory#1]
Could you please point out where the sources for the `libhook_lmkd.so` can be found? I assume that's also GPL licensed? Thanks in advance!

**Comment by OneB1ank** [comment]
I have not uploaded the source code of libhook_lmkd.so for now, the library used can be seen in NOTICE

**Comment by IzzySoft** [comment]
Wow, that was fast – thanks! Did you push it already (as I can't see it in the repo, which still claims the last commit was 3h ago)?

Meanwhile, your module is now included with [my repo](https://apt.izzysoft.de/magisk) (a Magisk repo solely accepting FOSS modules) :smiley:

**Comment by OneB1ank** [comment]
Thank you, but the core source code will not be uploaded for the time being, because the Chinese module forum is full of theft and non-compliance with the agreement.  What I am giving here is the authorization of the second modification module. Except that it cannot be sold commercially and does not indicate the author, other behaviors are allowed.

**Comment by IzzySoft** [comment]
Oh, I missed the 3 letters "n o t" :see_no_evil: OK, and thanks for your clarification! I've just marked it NonFreeComp then ("contains non-free components" – as "code not available" means one cannot perform [freedom-1](https://en.wikipedia.org/wiki/The_Free_Software_Definition#The_Four_Essential_Freedoms_of_Free_Software) (study/modify the code)).

Once you're able to upload the missing pieces and have them made available, be welcome to drop me a note so I remove that mark.
